name: CommandCooldown
authors: [ DonsuzTurk ]
version: ${project.version}
main: tr.donsuzturk.commandcooldown.Main
api-version: 1.17
description: İstediğiniz komutlara yeniden kullanım süresi eklemenizi sağlar.
